"""Strategy registry. Job J9, Phase 3.

╔══════════════════════════════════════════════════════════════════════════╗
║  OWNED BY BENCH. DO NOT EDIT THIS FILE ON ANOTHER BOX.                   ║
║                                                                          ║
║  Same for scripts/02_build_indexes.py and scripts/05_eval_retrieval.py.  ║
║  If you are on EMBED or LLM, your work goes in exactly ONE new file:     ║
║  services/rag_core/chunking/cN_*.py  (plus scripts/_gpu_embedder.py if   ║
║  you are EMBED on J1).                                                   ║
║                                                                          ║
║  Three people editing one dispatch function on three branches is the     ║
║  merge conflict that eats an evening nobody has. See Phase3-Parallel.md  ║
║  section 2.4 (J9) and section 4.                                         ║
╚══════════════════════════════════════════════════════════════════════════╝

Adding a strategy, once its chunker exists:
  1. import it below
  2. replace its `_Pending(...)` entry in STRATEGIES with the class
  3. that is all - 02_build_indexes.py and 05_eval_retrieval.py read from here

The Chunker protocol is in base.py and every strategy implements it unchanged.
Architecture.md 4.1 explains why these strategies differ in retrieval *unit*
rather than in how they cut long documents: this corpus has no long documents.
"""

from __future__ import annotations

from typing import Callable, Final

from .base import Chunker
from .c1_fixed import FixedChunker
from .c2_sentence_window import SentenceWindowChunker
from .c8_late import LateChunker
from .c5_metadata import MetadataChunker
from .c6_hierarchical import HierarchicalChunker
from .c7_doc2query import Doc2QueryChunker


class PendingStrategy(RuntimeError):
    """Raised when a strategy is registered but not yet implemented.

    Carries the owning job and box so the failure tells you who is building it
    rather than making you go and look it up.
    """


class _Pending:
    """Placeholder for a strategy someone else is building.

    Deliberately fails at *construction* time with a readable message rather
    than at some later attribute access with a stack trace.
    """

    def __init__(self, name: str, job: str, box: str, summary: str) -> None:
        self.name = name
        self.job = job
        self.box = box
        self.summary = summary

    def __call__(self, *args: object, **kwargs: object) -> Chunker:
        raise PendingStrategy(
            f"strategy '{self.name}' is not implemented yet.\n"
            f"  job:   {self.job}\n"
            f"  box:   {self.box}\n"
            f"  what:  {self.summary}\n"
            f"  file:  services/rag_core/chunking/{_FILENAMES[self.name]}\n"
            f"  See Phase3-Parallel.md section 2 for the full job description."
        )


_FILENAMES: Final[dict[str, str]] = {
    "c1": "c1_fixed.py",
    "c2": "c2_sentence_window.py",
    "c3": "c3_semantic.py",
    "c4": "c4_proposition.py",
    "c5": "c5_metadata.py",
    "c6": "c6_hierarchical.py",
    "c7": "c7_doc2query.py",
    "c8": "c8_late.py",
}


# name -> factory. Every value is callable as factory(embedder, **kwargs).
STRATEGIES: Final[dict[str, Callable[..., Chunker]]] = {
    "c1": FixedChunker,
    "c2": SentenceWindowChunker,
    "c3": _Pending(
        "c3", "J3", "EMBED",
        "semantic breakpoint at the 92nd percentile of consecutive-sentence "
        "cosine distance. Reuses J2's sentence embeddings - do not recompute.",
    ),
    "c4": _Pending(
        "c4", "J4/J6/J7", "LLM",
        "proposition: local LLM decomposes each passage into atomic facts. "
        "Overnight job, sharded and checkpointed. Never Groq (D11).",
    ),
    "c5": MetadataChunker,
    "c6": HierarchicalChunker,
    "c7": Doc2QueryChunker,
    "c8": LateChunker,
}

ALL_STRATEGIES: Final[tuple[str, ...]] = tuple(sorted(STRATEGIES))

# Strategies that need no new embeddings - they reuse the C1 vectors already on
# disk. This is why C5 and C6 sit on the GPU-less box (Phase3-Parallel.md 1).
REUSES_C1_VECTORS: Final[frozenset[str]] = frozenset({"c5", "c6"})

# Strategies that keep every C1 chunk and append to it. Their build can start
# from C1's vectors and embed only the new rows - see scripts/02c_build_derived.py.
EXTENDS_C1_VECTORS: Final[frozenset[str]] = frozenset({"c7"})


def get(name: str) -> Callable[..., Chunker]:
    """Look up a strategy factory by name.

    Raises KeyError with the valid set rather than a bare KeyError, because this
    is reached from a CLI flag and a typo should say so.
    """
    if name not in STRATEGIES:
        raise KeyError(
            f"unknown strategy '{name}'. Registered: {', '.join(ALL_STRATEGIES)}"
        )
    return STRATEGIES[name]


def implemented() -> tuple[str, ...]:
    """Strategies actually buildable right now."""
    return tuple(n for n in ALL_STRATEGIES if not isinstance(STRATEGIES[n], _Pending))


def pending() -> dict[str, str]:
    """Strategy name -> 'job on box', for status output."""
    return {
        n: f"{s.job} on {s.box}"
        for n, s in STRATEGIES.items()
        if isinstance(s, _Pending)
    }
